In [2]:
# Gerekli kütüphaneleri içe aktaralım
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.metrics import r2_score,mean_absolute_error, mean_squared_error
%matplotlib inline


In [3]:
df = pd.read_csv("diabetics_release.csv")

In [4]:
df.head()

Unnamed: 0  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  \
0           0            6      148             72             35        0   
1           1            1       85             66             29        0   
2           2            8      183             64              0        0   
3           3            1       89             66             23       94   
4           4            0      137             40             35      168   

    BMI  DiabetesPedigreeFunction  Age  Outcome  
0  33.6                     0.627   50        1  
1  26.6                     0.351   31        0  
2  23.3                     0.672   32        1  
3  28.1                     0.167   21        0  
4  43.1                     2.288   33        1

In [5]:
df.describe()

Unnamed: 0  Pregnancies     Glucose  BloodPressure  SkinThickness  \
count  768.000000   768.000000  768.000000     768.000000     768.000000   
mean   383.500000     3.845052  120.894531      69.105469      20.536458   
std    221.846794     3.369578   31.972618      19.355807      15.952218   
min      0.000000     0.000000    0.000000       0.000000       0.000000   
25%    191.750000     1.000000   99.000000      62.000000       0.000000   
50%    383.500000     3.000000  117.000000      72.000000      23.000000   
75%    575.250000     6.000000  140.250000      80.000000      32.000000   
max    767.000000    17.000000  199.000000     122.000000      99.000000   

          Insulin         BMI  DiabetesPedigreeFunction         Age  \
count  768.000000  768.000000                768.000000  768.000000   
mean    79.799479   31.992578                  0.471876   33.240885   
std    115.244002    7.884160                  0.331329   11.760232   
min      0.000000    0.000000                  0.078000   21.000000   
25%      0.000000   27.300000                  0.243750   24.000000   
50%     30.500000   32.000000                  0.372500   29.000000   
75%    127.250000   36.600000                  0.626250   41.000000   
max    846.000000   67.100000                  2.420000   81.000000   

          Outcome  
count  768.000000  
mean     0.348958  
std      0.476951  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      1.000000

In [6]:
df.drop("Unnamed: 0", axis=1, inplace=True)

In [7]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [8]:
columns_check = ["Glucose","BloodPressure",  'SkinThickness' , 'Insulin', "BMI" ]

for col in columns_check:
    zero_count = (df[col] == 0).sum()
    zero_percentage = (100 * zero_count / len(df)).round(2)
    print(f"{col}, {zero_count} , %{zero_percentage}")

Glucose, 5 , %0.65
BloodPressure, 35 , %4.56
SkinThickness, 227 , %29.56
Insulin, 374 , %48.7
BMI, 11 , %1.43


In [9]:
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

In [10]:
X_train , X_test , y_train, y_test = train_test_split(X,y, test_size=0.2 ,random_state=15)

In [11]:
columns_to_fill = columns_check

medians = {}
for col in columns_to_fill:
    median_value = X_train[X_train[col] != 0][col].median()
    medians[col] = median_value
    X_train[col] = X_train[col].replace(0, median_value)

for col in columns_to_fill:
    X_test[col] = X_test[col].replace(0, medians[col])

In [12]:
X_train.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   614.000000  614.000000     614.000000     614.000000  614.000000   
mean      3.907166  121.560261      72.612378      29.040717  142.477199   
std       3.385438   29.974412      12.165642       8.312217   80.879330   
min       0.000000   44.000000      24.000000       7.000000   14.000000   
25%       1.000000  100.000000      64.000000      25.000000  125.000000   
50%       3.000000  117.000000      72.000000      29.000000  129.500000   
75%       6.000000  139.750000      80.000000      32.000000  130.000000   
max      17.000000  199.000000     122.000000      63.000000  680.000000   

              BMI  DiabetesPedigreeFunction         Age  
count  614.000000                614.000000  614.000000  
mean    32.448208                  0.469948   33.285016  
std      6.862948                  0.328516   11.678337  
min     18.200000                  0.084000   21.000000  
25%     27.600000                  0.238250   24.000000  
50%     32.300000                  0.370500   29.000000  
75%     36.500000                  0.630750   40.000000  
max     67.100000                  2.420000   81.000000

In [13]:
X_test.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   154.000000  154.000000     154.000000     154.000000  154.000000   
mean      3.597403  122.038961      71.487013      29.376623  144.402597   
std       3.304818   32.320876      11.813495      10.513035  104.291511   
min       0.000000   61.000000      30.000000       7.000000   23.000000   
25%       1.000000   95.250000      64.000000      23.250000  108.250000   
50%       3.000000  117.000000      72.000000      29.000000  129.500000   
75%       5.750000  142.750000      80.000000      33.750000  129.500000   
max      13.000000  197.000000     106.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age  
count  154.000000                154.000000  154.000000  
mean    32.483117                  0.479565   33.064935  
std      6.946159                  0.343303   12.118519  
min     18.400000                  0.078000   21.000000  
25%     26.925000                  0.254000   24.000000  
50%     32.300000                  0.376500   28.000000  
75%     36.950000                  0.603750   41.000000  
max     55.000000                  2.329000   69.000000

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [16]:
# Metrics
def cal_model_metrics(true, predicted):
    accuracy = accuracy_score(true, predicted)
    class_report = classification_report(true, predicted)
    conf_matrix = confusion_matrix(true,predicted)
    return accuracy, class_report, conf_matrix

In [ ]:
models = {
        "randomForest" : RandomForestClassifier(),
        "svm" : SVC(),
        "LogisticRegression" : LogisticRegression(),
        "K-Neigbors Classifier" : KNeighborsClassifier(),
        "DecisionTree Classifier " : DecisionTreeClassifier(),
} # Classifier models

In [30]:
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train) # train datasındanda accuracysini almak için train aşırı yüksek test düşükse overfitting fazla 
    y_test_pred = model.predict(X_test)

    accuracy_train,class_report_train, conf_matrix_train = cal_model_metrics(y_train, y_train_pred)
    accuracy_test,class_report_test, conf_matrix_test = cal_model_metrics(y_test, y_test_pred)

    print(list(models.values())[i])

    print("---------------TRAİN------------------")

    print("Evaluation for Training Set")
    print("accuracy_score:",  accuracy_train)
    print("classification_report: ",class_report_train)
    print("confusion_matrix: \n",  conf_matrix_train)
    print("----------------TEST-----------------")

    print("Evaluation for Test Set")
    print("accuracy_score: ",  accuracy_test)
    print("classification_report: ",class_report_test)
    print("confusion_matrix: \n",  conf_matrix_test)
    print("---------------------------------")
    print("\n")

RandomForestClassifier()
---------------TRAİN------------------
Evaluation for Training Set
accuracy_score: 1.0
classification_report:                precision    recall  f1-score   support

           0       1.00      1.00      1.00       392
           1       1.00      1.00      1.00       222

    accuracy                           1.00       614
   macro avg       1.00      1.00      1.00       614
weighted avg       1.00      1.00      1.00       614

confusion_matrix: 
 [[392   0]
 [  0 222]]
----------------TEST-----------------
Evaluation for Test Set
accuracy_score:  0.7467532467532467
classification_report:                precision    recall  f1-score   support

           0       0.84      0.79      0.81       108
           1       0.57      0.65      0.61        46

    accuracy                           0.75       154
   macro avg       0.70      0.72      0.71       154
weighted avg       0.76      0.75      0.75       154

confusion_matrix: 
 [[85 23]
 [16 30]]
------

c:\Users\alkav\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [42]:
decision_param = {
    "criterion" : ["gini", "entropy", "log_loss"],
    "splitter" : ["best", "random"],
    "max_depth" : [2, 3, 4, 5, 6, 7, 8, 9, 10],
    "min_samples_split" : [2, 5, 10, 20, 50],
    "min_samples_leaf" : [1, 2, 4, 5, 10, 20],
    "max_features" : ["sqrt", "log2", None],
    "class_weight" : [None, "balanced"]
}

In [43]:
from sklearn.model_selection import GridSearchCV

In [44]:
grid = GridSearchCV(estimator=DecisionTreeClassifier(), param_grid=decision_param, n_jobs=-1)
grid.fit(X_train, y_train)
y_pred = grid.predict(X_test)

print("accuracy_score: ", accuracy_score(y_test, y_pred))
print("classification_report: ", classification_report(y_test, y_pred))
print("confussion_matrix: \n", confusion_matrix(y_test, y_pred))

accuracy_score:  0.7272727272727273
classification_report:                precision    recall  f1-score   support

           0       0.84      0.76      0.80       108
           1       0.54      0.65      0.59        46

    accuracy                           0.73       154
   macro avg       0.69      0.71      0.69       154
weighted avg       0.75      0.73      0.73       154

confussion_matrix: 
 [[82 26]
 [16 30]]


In [45]:
grid.best_params_

{'class_weight': None,
 'criterion': 'gini',
 'max_depth': 5,
 'max_features': None,
 'min_samples_leaf': 10,
 'min_samples_split': 50,
 'splitter': 'best'}

In [47]:
random_forest_param = {
    "n_estimators": [100, 200, 300, 500],
    "criterion": ["gini", "entropy"],
    "max_depth": [2, 3, 4, 5, 6, 7, 8, 9, 10],
    "min_samples_split": [2, 5, 10, 20, 50],
    "min_samples_leaf": [1, 2, 4, 5, 10, 20],
    "max_features": ["sqrt", "log2", None],
    "class_weight": [None, "balanced"]
}

In [49]:
grid = GridSearchCV(estimator=RandomForestClassifier(), param_grid=random_forest_param, n_jobs=-1)
grid.fit(X_train, y_train)
y_pred = grid.predict(X_test)

print("accuracy_score: ", accuracy_score(y_test, y_pred))
print("classification_report: ", classification_report(y_test, y_pred))
print("confussion_matrix: \n", confusion_matrix(y_test, y_pred))

accuracy_score:  0.7337662337662337
classification_report:                precision    recall  f1-score   support

           0       0.84      0.77      0.80       108
           1       0.55      0.65      0.59        46

    accuracy                           0.73       154
   macro avg       0.69      0.71      0.70       154
weighted avg       0.75      0.73      0.74       154

confussion_matrix: 
 [[83 25]
 [16 30]]


In [50]:
grid.best_params_

{'class_weight': None,
 'criterion': 'entropy',
 'max_depth': 9,
 'max_features': None,
 'min_samples_leaf': 5,
 'min_samples_split': 2,
 'n_estimators': 100}